# Generated by Django 4.1.1 on 2022-09-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_Title', models.CharField(blank=True, max_length=30)),
                ('Image_Desc', models.CharField(blank=True, max_length=255)),
                ('Image', models.ImageField(upload_to='Gallery')),
            ],
        ),
    ]
