# Generated by Django 4.1.1 on 2022-09-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_Title', models.CharField(blank=True, max_length=30)),
                ('Image_Desc', models.CharField(blank=True, max_length=255)),
                ('Image', models.ImageField(upload_to='Gallery')),
            ],
            options={
                'verbose_name_plural': 'Gallery',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Income_Source', models.CharField(blank=True, max_length=50)),
                ('Qualification', models.CharField(blank=True, max_length=50)),
                ('Years_of_Experience', models.IntegerField(blank=True)),
                ('Photo', models.ImageField(upload_to='Volunteers')),
                ('Facebook_Link', models.CharField(blank=True, max_length=255)),
                ('Twitter_Link', models.CharField(blank=True, max_length=255)),
                ('Linkedin_Link', models.CharField(blank=True, max_length=255)),
                ('Describtion', models.TextField(blank=True)),
            ],
        ),
    ]
