# Generated by Django 4.1.7 on 2023-03-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=15)),
                ('Message', models.TextField(max_length=255)),
                ('Date', models.DateField(auto_now=True)),
                ('Time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50, unique=True)),
                ('Date', models.DateField()),
                ('Time', models.TimeField(auto_now=True)),
                ('Location', models.CharField(max_length=255)),
                ('Photo1', models.ImageField(blank=True, upload_to='Events')),
                ('Photo2', models.ImageField(blank=True, upload_to='Events')),
                ('Photo3', models.ImageField(blank=True, upload_to='Events')),
                ('Photo4', models.ImageField(blank=True, upload_to='Events')),
                ('Photo5', models.ImageField(blank=True, upload_to='Events')),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('Location', models.CharField(max_length=255)),
                ('Photo', models.ImageField(upload_to='Projects')),
                ('Description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='Facebook_Link',
            new_name='Facebook_Username',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='Linkedin_Link',
            new_name='Linkedin_Username',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='Twitter_Link',
            new_name='Twitter_Username',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='Image_Desc',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='Income_Source',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='Employment',
            field=models.CharField(choices=[('Business Man', 'Business Man'), ('Teacher', 'Teacher'), ('Student', 'Student'), ('Govt Employee', 'Govt Emp'), ('Self Employed', 'Self Employed')], default='Student', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='Hobbies',
            field=models.CharField(default='Cricket', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='Years_of_Experience',
            field=models.IntegerField(),
        ),
    ]
