# Generated by Django 4.1.1 on 2022-09-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_facebook_link_volunteer_facebook_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Date_Time', models.DateTimeField(auto_now=True)),
                ('Location', models.CharField(max_length=255)),
                ('Photo', models.ImageField(upload_to='Projects')),
                ('Description', models.TextField()),
            ],
        ),
    ]
