# Generated by Django 4.1.1 on 2022-09-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Date_Time',
        ),
        migrations.AddField(
            model_name='project',
            name='Date',
            field=models.DateField(default='2022-09-17'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='Time',
            field=models.TimeField(auto_now=True),
        ),
    ]
