# Generated by Django 4.1.1 on 2022-09-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('Time', models.TimeField(auto_now=True)),
                ('Location', models.CharField(max_length=255)),
                ('Photo', models.ImageField(upload_to='Events')),
                ('Description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='Time',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='Hobbies',
            field=models.CharField(default='cricket', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Time',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='Years_of_Experience',
            field=models.IntegerField(),
        ),
    ]
