# Generated by Django 4.1.1 on 2022-09-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_event_remove_project_time_volunteer_hobbies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Photo',
        ),
        migrations.AddField(
            model_name='event',
            name='Photo1',
            field=models.ImageField(blank=True, upload_to='Events/<django.db.models.fields.CharField>'),
        ),
        migrations.AddField(
            model_name='event',
            name='Photo2',
            field=models.ImageField(blank=True, upload_to='Events/<django.db.models.fields.CharField>'),
        ),
        migrations.AddField(
            model_name='event',
            name='Photo3',
            field=models.ImageField(blank=True, upload_to='Events/<django.db.models.fields.CharField>'),
        ),
        migrations.AddField(
            model_name='event',
            name='Photo4',
            field=models.ImageField(blank=True, upload_to='Events/<django.db.models.fields.CharField>'),
        ),
        migrations.AddField(
            model_name='event',
            name='Photo5',
            field=models.ImageField(blank=True, upload_to='Events/<django.db.models.fields.CharField>'),
        ),
    ]
