# Generated by Django 4.1.1 on 2022-09-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_remove_event_photo_event_photo1_event_photo2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Photo1',
            field=models.ImageField(blank=True, upload_to='Events'),
        ),
        migrations.AlterField(
            model_name='event',
            name='Photo2',
            field=models.ImageField(blank=True, upload_to='Events'),
        ),
        migrations.AlterField(
            model_name='event',
            name='Photo3',
            field=models.ImageField(blank=True, upload_to='Events'),
        ),
        migrations.AlterField(
            model_name='event',
            name='Photo4',
            field=models.ImageField(blank=True, upload_to='Events'),
        ),
        migrations.AlterField(
            model_name='event',
            name='Photo5',
            field=models.ImageField(blank=True, upload_to='Events'),
        ),
    ]
